name: Build Kivy APK
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update -y
        sudo apt install -y python3-pip build-essential git zip unzip openjdk-17-jdk libtool autoconf automake
        pip install --upgrade pip setuptools wheel
        pip install buildozer cython virtualenv yt-dlp ffmpeg-python kivymd

    - name: Set environment variables
      run: |
        echo "ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
        echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/36.0.0:$PATH" >> $GITHUB_ENV

    - name: Download and setup Android Command Line Tools
      run: |
        mkdir -p $HOME/.buildozer/android/platform/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O tools.zip
        unzip tools.zip -d $HOME/.buildozer/android/platform/android-sdk/cmdline-tools
        mv $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/cmdline-tools $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest
        mkdir -p $HOME/.buildozer/android/platform/android-sdk/tools/bin
        ln -s $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager $HOME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager
        chmod +x $HOME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager

    - name: Accept licenses and install SDK packages
      run: |
        yes | $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses
        yes | $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-33" "build-tools;36.0.0"

    - name: Download Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip -O ndk.zip
        unzip ndk.zip -d $HOME/.buildozer/android/platform/
        echo "ANDROID_NDK_HOME=$HOME/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV

    - name: Configure Buildozer
      run: |
        sed -i 's/package.name = .*/package.name = youtubedownloader/' buildozer.spec
        sed -i 's/package.domain = .*/package.domain = org.ryen/' buildozer.spec
        sed -i 's/# (str) Application title.*/title = YouTube Downloader/' buildozer.spec
        sed -i 's/source.include_exts = .*/source.include_exts = py,kv,png,jpg,jpeg,txt,md/' buildozer.spec

    - name: Build APK
      run: |
        buildozer -v android debug
      env:
        ANDROIDSDK: $HOME/.buildozer/android/platform/android-sdk
        ANDROIDNDK: $HOME/.buildozer/android/platform/android-ndk-r25b

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: YouTubeDownloader-APK
        path: bin/*.apk
