name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Accept all Android SDK licenses
      run: yes | sdkmanager --licenses

    - name: Install Android Build Tools (required for AIDL)
      run: |
        sdkmanager "build-tools;36.0.0"
        ls "${ANDROID_SDK_ROOT}/build-tools"

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: YouTubeDownloader.apk
        path: bin/*.apk
